# this is the build file for project swarm
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

AS=/usr/bin/gcc
CXX=/usr/bin/gcc
CC=/usr/bin/gcc
CU=/usr/bin/clang
MM=/usr/bin/gcc
GC=/usr/bin/go
MXX=/usr/bin/gcc
RC=/home/danielboll/.cargo/bin/rustc

AR=/usr/bin/ar
GCAR=/usr/bin/go
RCAR=/home/danielboll/.cargo/bin/rustc
LD=/usr/bin/g++
GCLD=/usr/bin/go
RCLD=/home/danielboll/.cargo/bin/rustc
SH=/usr/bin/g++
RCSH=/home/danielboll/.cargo/bin/rustc

swarm_LD=/usr/bin/g++
swarm_CXX=/usr/bin/gcc
swarm_CXX=/usr/bin/gcc
swarm-lib_AR=/usr/bin/ar
swarm-lib_CXX=/usr/bin/gcc
swarm-lib_CXX=/usr/bin/gcc

swarm_CXXFLAGS=-m64 -g -O0 -std=c++23 -Iinclude -isystem /home/danielboll/.xmake/packages/r/raylib-cpp/v5.0.2/3943fd42ee6a4420ae9a4b0c25bc35cd/include -isystem /home/danielboll/.xmake/packages/r/raylib/5.0/aeed26e13a7a466f9d7c7ad6dd3b75c2/include -isystem /home/danielboll/.xmake/packages/f/flecs/v4.0.0/1cc9d6a21a0d426687c5fbb7f5b4ed05/include
swarm_CXXFLAGS=-m64 -g -O0 -std=c++23 -Iinclude -isystem /home/danielboll/.xmake/packages/r/raylib-cpp/v5.0.2/3943fd42ee6a4420ae9a4b0c25bc35cd/include -isystem /home/danielboll/.xmake/packages/r/raylib/5.0/aeed26e13a7a466f9d7c7ad6dd3b75c2/include -isystem /home/danielboll/.xmake/packages/f/flecs/v4.0.0/1cc9d6a21a0d426687c5fbb7f5b4ed05/include
swarm_LDFLAGS=-m64 -Lbuild/linux/x86_64/debug -L/home/danielboll/.xmake/packages/r/raylib/5.0/aeed26e13a7a466f9d7c7ad6dd3b75c2/lib -L/home/danielboll/.xmake/packages/f/flecs/v4.0.0/1cc9d6a21a0d426687c5fbb7f5b4ed05/lib -lswarm-lib -lraylib -lXrandr -lXinerama -lXcursor -lXrender -lX11 -lXi -lXfixes -lXext -lX11-xcb -lxcb -lxcb-composite -lxcb-damage -lxcb-dbe -lxcb-dpms -lxcb-dri2 -lxcb-dri3 -lxcb-glx -lxcb-present -lxcb-randr -lxcb-record -lxcb-render -lxcb-res -lxcb-screensaver -lxcb-shape -lxcb-shm -lxcb-sync -lxcb-xf86dri -lxcb-xfixes -lxcb-xinerama -lxcb-xinput -lxcb-xkb -lxcb-xtest -lxcb-xv -lxcb-xvmc -lXau -lXdmcp -lOpenGL -lflecs_static -ldl -lm -lpthread
swarm-lib_CXXFLAGS=-m64 -g -O0 -std=c++23 -Iinclude -isystem /home/danielboll/.xmake/packages/r/raylib-cpp/v5.0.2/3943fd42ee6a4420ae9a4b0c25bc35cd/include -isystem /home/danielboll/.xmake/packages/r/raylib/5.0/aeed26e13a7a466f9d7c7ad6dd3b75c2/include -isystem /home/danielboll/.xmake/packages/f/flecs/v4.0.0/1cc9d6a21a0d426687c5fbb7f5b4ed05/include
swarm-lib_CXXFLAGS=-m64 -g -O0 -std=c++23 -Iinclude -isystem /home/danielboll/.xmake/packages/r/raylib-cpp/v5.0.2/3943fd42ee6a4420ae9a4b0c25bc35cd/include -isystem /home/danielboll/.xmake/packages/r/raylib/5.0/aeed26e13a7a466f9d7c7ad6dd3b75c2/include -isystem /home/danielboll/.xmake/packages/f/flecs/v4.0.0/1cc9d6a21a0d426687c5fbb7f5b4ed05/include
swarm-lib_ARFLAGS=-cr

default:  swarm swarm-lib

all:  swarm swarm-lib

.PHONY: default all  swarm swarm-lib

swarm: build/linux/x86_64/debug/swarm
build/linux/x86_64/debug/swarm: build/linux/x86_64/debug/libswarm-lib.a build/.objs/swarm/linux/x86_64/debug/src/main.cpp.o
	@echo linking.debug swarm
	@mkdir -p build/linux/x86_64/debug
	$(VV)$(swarm_LD) -o build/linux/x86_64/debug/swarm build/.objs/swarm/linux/x86_64/debug/src/main.cpp.o $(swarm_LDFLAGS)

build/.objs/swarm/linux/x86_64/debug/src/main.cpp.o: src/main.cpp
	@echo compiling.debug src/main.cpp
	@mkdir -p build/.objs/swarm/linux/x86_64/debug/src
	$(VV)$(swarm_CXX) -c $(swarm_CXXFLAGS) -o build/.objs/swarm/linux/x86_64/debug/src/main.cpp.o src/main.cpp

swarm-lib: build/linux/x86_64/debug/libswarm-lib.a
build/linux/x86_64/debug/libswarm-lib.a: build/.objs/swarm-lib/linux/x86_64/debug/lib/systems/render.cpp.o build/.objs/swarm-lib/linux/x86_64/debug/lib/systems/movement.cpp.o
	@echo linking.debug libswarm-lib.a
	@mkdir -p build/linux/x86_64/debug
	$(VV)$(swarm-lib_AR) $(swarm-lib_ARFLAGS) build/linux/x86_64/debug/libswarm-lib.a build/.objs/swarm-lib/linux/x86_64/debug/lib/systems/render.cpp.o build/.objs/swarm-lib/linux/x86_64/debug/lib/systems/movement.cpp.o

build/.objs/swarm-lib/linux/x86_64/debug/lib/systems/render.cpp.o: lib/systems/render.cpp
	@echo compiling.debug lib/systems/render.cpp
	@mkdir -p build/.objs/swarm-lib/linux/x86_64/debug/lib/systems
	$(VV)$(swarm-lib_CXX) -c $(swarm-lib_CXXFLAGS) -o build/.objs/swarm-lib/linux/x86_64/debug/lib/systems/render.cpp.o lib/systems/render.cpp

build/.objs/swarm-lib/linux/x86_64/debug/lib/systems/movement.cpp.o: lib/systems/movement.cpp
	@echo compiling.debug lib/systems/movement.cpp
	@mkdir -p build/.objs/swarm-lib/linux/x86_64/debug/lib/systems
	$(VV)$(swarm-lib_CXX) -c $(swarm-lib_CXXFLAGS) -o build/.objs/swarm-lib/linux/x86_64/debug/lib/systems/movement.cpp.o lib/systems/movement.cpp

clean:  clean_swarm clean_swarm-lib

clean_swarm:  clean_swarm-lib
	@rm -rf build/linux/x86_64/debug/swarm
	@rm -rf build/linux/x86_64/debug/swarm.sym
	@rm -rf build/.objs/swarm/linux/x86_64/debug/src/main.cpp.o

clean_swarm-lib: 
	@rm -rf build/linux/x86_64/debug/libswarm-lib.a
	@rm -rf build/linux/x86_64/debug/swarm-lib.sym
	@rm -rf build/.objs/swarm-lib/linux/x86_64/debug/lib/systems/render.cpp.o
	@rm -rf build/.objs/swarm-lib/linux/x86_64/debug/lib/systems/movement.cpp.o

